# Generated by Django 3.1.5 on 2021-02-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0031_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
