# Generated by Django 3.1.5 on 2021-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0032_auto_20210210_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
