# Generated by Django 3.1.5 on 2021-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0033_auto_20210213_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
