# Generated by Django 3.1.5 on 2021-02-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0034_auto_20210213_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='policestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policestation_contact_no', models.CharField(default='000000', max_length=100)),
                ('policestation_address', models.CharField(blank=True, max_length=500)),
                ('policestation_area', models.CharField(max_length=50)),
                ('policestation_city', models.CharField(max_length=50)),
                ('policestation_name', models.CharField(max_length=100)),
                ('inspector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.inspector')),
            ],
        ),
    ]
