# Generated by Django 3.1.5 on 2021-03-09 09:58

import citizen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0035_policestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='contact_no',
            field=models.IntegerField(default='000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='contact_no',
            field=models.IntegerField(default='000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, validators=[citizen.models.validate_geeks_mail]),
        ),
    ]
