# Generated by Django 3.1.5 on 2021-03-09 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0036_auto_20210309_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='firstname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='lastname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='firstname',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='lastname',
            field=models.TextField(max_length=50),
        ),
    ]
