# Generated by Django 3.1.5 on 2021-03-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0037_auto_20210309_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioner',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
