# Generated by Django 3.1.5 on 2021-03-10 12:53

import citizen.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0038_auto_20210309_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='firstname',
            field=models.CharField(max_length=50, validators=[citizen.models.citizenfvalidation]),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='lastname',
            field=models.CharField(max_length=50, validators=[citizen.models.citizenlvalidation]),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='city',
            field=models.CharField(max_length=50, validators=[citizen.models.commissionerfvalidation]),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='firstname',
            field=models.CharField(max_length=50, validators=[citizen.models.commissionerfvalidation]),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='lastname',
            field=models.CharField(max_length=50, validators=[citizen.models.commissionerlvalidation]),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format of intergers only . Up to 10 digits allowed.', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='firstname',
            field=models.CharField(max_length=50, validators=[citizen.models.validation]),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='lastname',
            field=models.CharField(max_length=50, validators=[citizen.models.lastname_validation]),
        ),
    ]
