# Generated by Django 3.1.5 on 2021-03-10 13:00

import citizen.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0039_auto_20210310_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format of intergers only . Up to 10 digits allowed.', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='commissioner',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format of intergers only . Up to 10 digits allowed.', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='policestation_city',
            field=models.CharField(max_length=50, validators=[citizen.models.lastname_validation]),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='policestation_contact_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format of intergers only . Up to 10 digits allowed.', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='policestation_name',
            field=models.CharField(max_length=100, validators=[citizen.models.lastname_validation]),
        ),
    ]
