# Generated by Django 3.1.5 on 2021-03-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0040_auto_20210310_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
