# Generated by Django 3.1.5 on 2021-03-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0042_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='dob',
            field=models.DateField(),
        ),
    ]
