# Generated by Django 3.1.5 on 2021-03-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0043_auto_20210311_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
