# Generated by Django 3.1.5 on 2021-03-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0045_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='address',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='contact_no',
        ),
    ]
