# Generated by Django 3.1.5 on 2021-03-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0048_auto_20210311_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='proof_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='proof_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video file'),
        ),
    ]
