# Generated by Django 3.1.5 on 2021-03-15 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0049_auto_20210312_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
