# Generated by Django 3.1.5 on 2021-03-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0050_auto_20210315_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
