# Generated by Django 3.1.5 on 2021-03-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0054_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
