# Generated by Django 3.1.5 on 2021-03-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0060_fir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FIR',
        ),
    ]
