# Generated by Django 3.1.5 on 2021-03-17 07:00

import citizen.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0063_delete_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIR_no', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=50, validators=[citizen.models.commissionerfvalidation])),
                ('lastname', models.CharField(max_length=50, validators=[citizen.models.commissionerlvalidation])),
                ('proof_img', models.FileField(blank=True, null=True, upload_to='images/')),
                ('proof_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video file')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('FIR_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=200, validators=[citizen.models.validate_geeks_mail])),
                ('FIR_description', models.CharField(max_length=500)),
                ('contact_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format of intergers only . Up to 10 digits allowed.', regex='^\\+?1?\\d{10}$')])),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.citizen')),
                ('crime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.crime_category')),
                ('policestation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.policestation')),
                ('subcrime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.sub_crime')),
            ],
        ),
    ]
