# Generated by Django 3.1.5 on 2021-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0064_fir'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
