# Generated by Django 3.1.5 on 2021-03-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0067_auto_20210318_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
