# Generated by Django 3.1.5 on 2021-04-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0069_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='policestation_name',
            new_name='pname',
        ),
    ]
