# Generated by Django 3.0 on 2021-08-05 04:58

import citizen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0070_auto_20210401_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=20, validators=[citizen.models.role_validation]),
        ),
    ]
